title: Shummus Shah
description: Learn a little bit more about me.
author: Shummus Shah
email: shummus.shah@outlook.com
phone: 07563159742
github: https://github.com/shahs210
about: I am a Wealth Manager at <a href="https://www.mazars.co.uk/Home/Services/Financial-Planning" target="_blank">Mazars Financial Planning</a> and on a journey to learn how to code. I enjoy exploring technologies and knowing how processes work.
disqus_shortname: programming
google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/shummuss/"
    - icon: fa-twitter
      link: "https://twitter.com/shummuss"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/shummusshah/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/shahs210"

share:
  twitter_username: ShummusS
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://shahs210.github.io/shummuss-blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
